version: "3.9"
services:
  api:
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=dev-secret-key-change
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
